// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#pragma once

#if defined(MGOS)
#include <mgos.h>
#endif

#if defined(HAVE_PERROR)
#include <stdio.h>
#endif

#if defined(MGOS)
#define PERROR(msg) LOG(LL_ERROR, ((msg)))
#elif defined(HAVE_PERROR)
#define PERROR(msg) perror(msg)
#else
#define PERROR(msg)
#endif
